seed_everything: 1293
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        refresh_rate: 10
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: epoch={epoch:03d}_mse={val/MSE:.2f}_mae={val/MAE:.2f}
        monitor: val/MAE
        verbose: True
        save_last: True
        auto_insert_metric_name: False
        save_on_train_epoch_end: False
        save_weights_only: True
        mode: min
  benchmark: True
  accelerator: auto
  devices: auto
  num_sanity_val_steps: 0
  detect_anomaly: True
  max_epochs: 300
model:
  hparams:
    batch_size_train: 4
    batch_size_val: 1
    num_workers: 4
    lr: 0.001
    weight_decay: 1.0e-5
    model_name: 'VideoSwin'
    loss_name: 'Bayesian'
    dataset_name: 'BayesianTemporal'
    log_para: 1
    model:
      pretrained: False
    loss:
      device: 'cuda'
      use_background: True
    post_prob:
      device: 'cuda'
      sigma: 8.0
      c_size: 224
      stride: 16
      background_ratio: 0.15
      use_background: True
    dataset:
      root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/fdst'
      crop_size: 224
      seq_len: 16
      downsample: 1
      log_para: 1
      is_grey: False