seed_everything: 1293
trainer:
  callbacks:
    class_path: pytorch_lightning.callbacks.RichProgressBar
    init_args:
      refresh_rate: 10
    class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      filename: epoch={epoch:03d}_mse={val/MSE:.2f}_mae={val/MAE:.2f}_nae={val/NAE:.2f}
      monitor: val/NAE
      verbose: True
      save_last: True
      auto_insert_metric_name: False
      save_on_train_epoch_end: False
      save_weights_only: True
      mode: min
      save_top_k: 3
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: 'logs'
      version: jhu_swinsdcnet_base_newdmap_novgg_300epoch
  benchmark: True
  accelerator: auto
  devices: auto
  num_sanity_val_steps: 0
  detect_anomaly: True
  max_epochs: 300
model:
  hparams:
    batch_size_train: 8
    batch_size_val: 1
    num_workers: 16
    lr: 0.0001
    weight_decay: 1.0e-4
    model_name: 'SwinSDCNet3'
    loss_name: 'MSE'
    dataset_name: 'Scale'
    log_para: 10
    patch_size: 3584
    model:
      pretrained: true
    loss:
      reduction: 'mean'
    dataset:
      root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/jhu'
      crop_size: 512
      downsample: 16
      log_para: 1
      is_grey: False
      unit_size: 32
      type: 1
      scale_level: 10
      model_level: 3