seed_everything: 1293
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        refresh_rate: 10
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: epoch={epoch:03d}_mse={val/MSE:.6f}
        monitor: val/MSE
        verbose: True
        save_last: True
        auto_insert_metric_name: False
        save_on_train_epoch_end: False
        save_weights_only: True
        mode: min
  benchmark: True
  accelerator: auto
  devices: auto
  num_sanity_val_steps: 0
  detect_anomaly: True
  max_epochs: 300
model:
  hparams:
    batch_size_train: 4
    batch_size_val: 1
    num_workers: 4
    lr: 0.001
    train_split: 'data/SmartCity/train.txt'
    val_split: 'data/SmartCity/val.txt'
    test_split: 'data/SmartCity/test.txt'
    model_name: 'CSRNet'
    loss_name: 'OT'
    dataset_name: 'Binary'
    wot: 0.1
    wtv: 0.01
    model:
      load_weights: true
    loss:
      c_size: 512
      stride: 8
      norm_cood: 0
      num_of_iter_in_ot: 100
      reg: 10.0
    dataset:
      dname: 'SmartCity'
      root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/SmartCity'
      crop_size: 512
      downsample: 8
      log_para: 1
  