seed_everything: 1293
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        refresh_rate: 10
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: epoch={epoch:03d}_mse={val/MSE:.2f}_mae={val/MAE:.2f}
        monitor: val/MSE
        verbose: True
        save_last: True
        auto_insert_metric_name: False
        save_on_train_epoch_end: False
        save_weights_only: True
        mode: min
  benchmark: True
  accelerator: auto
  devices: auto
  num_sanity_val_steps: 0
  detect_anomaly: True
  max_epochs: 100
model:
  hparams:
    batch_size_train: 4
    batch_size_val: 1
    num_workers: 4
    lr: 0.0001
    train_split: null
    val_split: 'data/ShanghaiTechA/val.txt'
    test_split: 'data/ShanghaiTechA/test.txt'
    model_name: 'SACANet'
    loss_name: 'Bayesian'
    dataset_name: 'Bayesian'
    log_para: 1
    model:
      load_weights: false
    loss:
      device: 'cuda'
      use_background: true
    post_prob:
      device: 'cuda'
      sigma: 8.0
      c_size: 784
      stride: 8
      background_ratio: 0.15
      use_background: True
    dataset_train:
      dname: 'SHHA'
      root: '/mnt/data/smartcity/SHHA/train'
      crop_size: 784
      downsample: 8
      log_para: 1
    dataset_val:
      dname: 'SHHA'
      root: '/mnt/data/smartcity/SHHA/test'
      crop_size: 784
      downsample: 8
      log_para: 1
    dataset_test:
      dname: 'SHHA'
      root: '/mnt/data/smartcity/SHHA/test'
      crop_size: 784
      downsample: 8
      log_para: 1
  