seed_everything: 1293
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        refresh_rate: 10
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: epoch={epoch:03d}_mse={val/MSE:.2f}_mae={val/MAE:.2f}
        monitor: val/MAE
        verbose: True
        save_last: True
        auto_insert_metric_name: False
        save_on_train_epoch_end: False
        save_weights_only: True
        mode: min
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: 'logs'
      version: vidcrowd_vcformer5
  benchmark: True
  accelerator: auto
  devices: auto
  num_sanity_val_steps: 0
  detect_anomaly: True
  max_epochs: 120
model:
  hparams:
    batch_size_train: 2
    batch_size_val: 1
    num_workers: 16
    lr: 0.001
    weight_decay: 1.0e-4
    model_name: 'VCFormer'
    loss_name: 'MSE'
    dataset_name: 'DensityTemporal'
    # loss_name: 'Bayesian'
    # dataset_name: 'BayesianTemporal'
    log_para: 100
    patch_size: 512
    model:
      image_size: 512
      image_patch_size: 16
      frames: 8
      dim: 1024
      depth: 3
      heads: 8
      mlp_dim: 1024
      dropout: 0.1
      emb_dropout: 0.1
    # loss:
    #   device: 'cuda'
    #   use_background: true
    # post_prob:
    #   device: 'cuda'
    #   sigma: 8.0
    #   c_size: 512
    #   stride: 16
    #   background_ratio: 0.15
    #   use_background: True
    loss:
      reduction: 'mean'
    dataset:
      root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/vidcrowd2'
      crop_size: 512
      downsample: 16
      seq_len: 8
      log_para: 1
      is_grey: False
      unit_size: 512
      channel_first: true